
from   PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(559, 298)
        MainWindow.setAnimated(True)
        MainWindow.setWindowIcon(QtGui.QIcon('mp3.ico'))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.START = QtWidgets.QPushButton(self.centralwidget)
        self.START.setGeometry(QtCore.QRect(10, 240, 111, 41))
        self.START.setAutoDefault(False)
        self.START.setObjectName("START")

        self.male = QtWidgets.QRadioButton(self.centralwidget)
        self.male.setGeometry(QtCore.QRect(440, 100, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.male.setFont(font)
        self.male.setObjectName("male")
        self.male.setChecked(True)

        self.Female = QtWidgets.QRadioButton(self.centralwidget)
        self.Female.setGeometry(QtCore.QRect(440, 120, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Female.setFont(font)
        self.Female.setObjectName("Female")

        self.Unspecified = QtWidgets.QRadioButton(self.centralwidget)
        self.Unspecified.setGeometry(QtCore.QRect(440, 140, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Unspecified.setFont(font)
        self.Unspecified.setObjectName("Unspecified")

        self.ontop = QtWidgets.QCheckBox(self.centralwidget)
        self.ontop.setGeometry(QtCore.QRect(290, 100, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ontop.setFont(font)
        self.ontop.setObjectName("ontop")

        self.chooseid = QtWidgets.QCheckBox(self.centralwidget)
        self.chooseid.setGeometry(QtCore.QRect(290, 120, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.chooseid.setFont(font)
        self.chooseid.setObjectName("chooseid")

        self.Nation = QtWidgets.QLineEdit(self.centralwidget)
        self.Nation.setGeometry(QtCore.QRect(110, 100, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Nation.setFont(font)
        self.Nation.setMaxLength(3)
        self.Nation.setAlignment(QtCore.Qt.AlignCenter)
        self.Nation.setObjectName("Nation")
        rx = QtCore.QRegExp("^[a-z- A-Z-]{100}")
        val = QtGui.QRegExpValidator(rx)
        self.Nation.setValidator(val)

        self.Issuing = QtWidgets.QLineEdit(self.centralwidget)
        self.Issuing.setGeometry(QtCore.QRect(210, 100, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Issuing.setFont(font)
        self.Issuing.setMaxLength(3)
        self.Issuing.setAlignment(QtCore.Qt.AlignCenter)
        self.Issuing.setObjectName("Issuing")
        self.Issuing.setValidator(val)

        self.Exp = QtWidgets.QLineEdit(self.centralwidget)
        self.Exp.setGeometry(QtCore.QRect(10, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Exp.setFont(font)
        self.Exp.setMaxLength(10)
        self.Exp.setAlignment(QtCore.Qt.AlignCenter)
        self.Exp.setObjectName("Exp")
        rx_3 = QtCore.QRegExp("[0-9./]{100}")
        val_3 = QtGui.QRegExpValidator(rx_3)
        self.Exp.setValidator(val_3)


        self.Numb = QtWidgets.QLineEdit(self.centralwidget)
        self.Numb.setGeometry(QtCore.QRect(110, 170, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Numb.setFont(font)
        self.Numb.setMaxLength(9)
        self.Numb.setAlignment(QtCore.Qt.AlignCenter)
        self.Numb.setObjectName("Numb")
        rx_2 = QtCore.QRegExp("^[a-zA-Z0-9]{100}")
        val_2 = QtGui.QRegExpValidator(rx_2)
        self.Numb.setValidator(val_2)

        self.Extra = QtWidgets.QLineEdit(self.centralwidget)
        self.Extra.setGeometry(QtCore.QRect(290, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Extra.setFont(font)
        self.Extra.setMaxLength(14)
        self.Extra.setAlignment(QtCore.Qt.AlignCenter)
        self.Extra.setObjectName("Extra")
        self.Extra.setValidator(val_2)

        self.Name = QtWidgets.QLineEdit(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(10, 30, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Name.setFont(font)
        self.Name.setMaxLength(24)
        self.Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Name.setObjectName("Name")
        self.Name.setValidator(val)

        self.Surname = QtWidgets.QLineEdit(self.centralwidget)
        self.Surname.setGeometry(QtCore.QRect(290, 30, 251, 31))
        font = QtGui.QFont() #
        font.setPointSize(13)
        self.Surname.setFont(font)
        self.Surname.setMaxLength(24)
        self.Surname.setAlignment(QtCore.Qt.AlignCenter)
        self.Surname.setObjectName("Surname")
        self.Surname.setValidator(val)

        self.DOB = QtWidgets.QLineEdit(self.centralwidget)
        self.DOB.setGeometry(QtCore.QRect(10, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DOB.setFont(font)
        self.DOB.setMaxLength(10)
        self.DOB.setAlignment(QtCore.Qt.AlignCenter)
        self.DOB.setObjectName("DOB")
        self.DOB.setValidator(val_3)


        self.label = QtWidgets.QLabel(self.centralwidget) # output window for result
        self.label.setGeometry(QtCore.QRect(130, 230, 401, 61))
        self.label.setFont(QtGui.QFont("OCR-B 10 BT", 11, QtGui.QFont.Light))
        self.label.setWordWrap(True)
        self.label.setLineWidth(2)
        self.label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label.setText("     Your MRZ will be here...")
        self.label.setIndent(4)
        self.label.setObjectName("label")

        self.Nationality_lbl = QtWidgets.QLabel(self.centralwidget)
        self.Nationality_lbl.setGeometry(QtCore.QRect(110, 80, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Nationality_lbl.setFont(font)
        self.Nationality_lbl.setObjectName("Nationality_lbl")

        self.Issuing_State = QtWidgets.QLabel(self.centralwidget)
        self.Issuing_State.setGeometry(QtCore.QRect(210, 80, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Issuing_State.setFont(font)
        self.Issuing_State.setObjectName("Issuing_State")

        self.Name_and_Midlename = QtWidgets.QLabel(self.centralwidget)
        self.Name_and_Midlename.setGeometry(QtCore.QRect(10, 10, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Name_and_Midlename.setFont(font)
        self.Name_and_Midlename.setObjectName("Name_and_Midlename")

        self.Surname_lbl = QtWidgets.QLabel(self.centralwidget)
        self.Surname_lbl.setGeometry(QtCore.QRect(290, 10, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Surname_lbl.setFont(font)
        self.Surname_lbl.setObjectName("Surname_lbl")

        self.dob_lbl = QtWidgets.QLabel(self.centralwidget)
        self.dob_lbl.setGeometry(QtCore.QRect(10, 80, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dob_lbl.setFont(font)
        self.dob_lbl.setObjectName("dob_lbl")

        self.Expire_date_lbl = QtWidgets.QLabel(self.centralwidget)
        self.Expire_date_lbl.setGeometry(QtCore.QRect(10, 150, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Expire_date_lbl.setFont(font)
        self.Expire_date_lbl.setObjectName("Expire_date")

        self.Document_Number = QtWidgets.QLabel(self.centralwidget)
        self.Document_Number.setGeometry(QtCore.QRect(110, 150, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Document_Number.setFont(font)
        self.Document_Number.setObjectName("Document_Number")

        self.Extra_Info = QtWidgets.QLabel(self.centralwidget)
        self.Extra_Info.setGeometry(QtCore.QRect(290, 150, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Extra_Info.setFont(font)
        self.Extra_Info.setObjectName("Extra_Info")

        self.signature = QtWidgets.QLabel(self.centralwidget)
        self.signature.setGeometry(QtCore.QRect(440, 175, 91, 30))
        self.signature.setFont(QtGui.QFont("FG Rebecca Script", 11, QtGui.QFont.Light))
        self.signature.setWordWrap(True)
        self.signature.setLineWidth(2)
        self.signature.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.signature.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.signature.setIndent(4)
        self.signature.setObjectName("Signature")

        self.mounth = QtWidgets.QLabel(self.centralwidget)
        self.mounth.setGeometry(QtCore.QRect(440, 210, 91, 30))
        self.mounth.setFont(QtGui.QFont("OCR-B 10 BT", 11, QtGui.QFont.Light))
        self.mounth.setWordWrap(True)
        self.mounth.setLineWidth(2)
        self.mounth.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.mounth.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.mounth.setIndent(4)
        self.mounth.setObjectName("Mounth")


        self.sex = QtWidgets.QLabel(self.centralwidget)
        self.sex.setGeometry(QtCore.QRect(440, 80, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sex.setFont(font)
        self.sex.setObjectName("sex")

        self.Fix = QtWidgets.QLabel(self.centralwidget)
        self.Fix.setGeometry(QtCore.QRect(290, 80, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Fix.setFont(font)
        self.Fix.setObjectName("Fix")

        self.by = QtWidgets.QLabel(self.centralwidget)
        self.by.setGeometry(QtCore.QRect(500, 275, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.by.setFont(font)
        self.by.setStyleSheet('color:grey')
        self.by.setObjectName("by")

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRZ Calculator"))
        self.START.setText(_translate("MainWindow", "Calculate MRZ"))
        self.male.setText(_translate("MainWindow", "Male"))
        self.Female.setText(_translate("MainWindow", "Female"))
        self.Unspecified.setText(_translate("MainWindow", "Unspec."))
        self.ontop.setText(_translate("MainWindow", "always on top"))
        self.chooseid.setText(_translate("MainWindow", "switch type"))
        self.Nationality_lbl.setText(_translate("MainWindow", "Nationality"))
        self.Issuing_State.setText(_translate("MainWindow", "Issuing St"))
        self.Name_and_Midlename.setText(_translate("MainWindow", "Name & Midlename"))
        self.Surname_lbl.setText(_translate("MainWindow", "Surname"))
        self.dob_lbl.setText(_translate("MainWindow", "DB dd.mm.yyyy"))
        self.Expire_date_lbl.setText(_translate("MainWindow", "Exp dd.mm.yyyy"))
        self.Document_Number.setText(_translate("MainWindow", "Document Number"))
        self.Extra_Info.setText(_translate("MainWindow", "Extra Info"))
        self.sex.setText(_translate("MainWindow", "sex"))
        self.Fix.setText(_translate("MainWindow", "Fix"))
        self.signature.setText(_translate("MainWindow", "Signature"))
        self.mounth.setText(_translate("MainWindow", "Mounth"))
        self.by.setText(_translate("MainWindow", "by sova"))
